// GENERATED by tools/build_content.py from the fact-checked study content in content/*.json.
// Edit the JSON and re-run the script rather than editing this file.

void loadContent() {
  content_cells();
  content_bones();
  content_muscles();
  content_nervous();
  content_heart();
  content_lungs();
  content_digestion();
  content_kidneys();
  content_hormones();
  content_immune();
}

void content_cells() {
  topic("cells", "CELLS", "cell");
}

void content_bones() {
  topic("bones", "BONES", "skeleton");
}

void content_muscles() {
  topic("muscles", "MUSCLES", "muscles");
}

void content_nervous() {
  topic("nervous", "NERVOUS SYSTEM", "neuron", "brain");
}

void content_heart() {
  topic("heart", "HEART & BLOOD", "heart");
}

void content_lungs() {
  topic("lungs", "LUNGS", "lungs");
}

void content_digestion() {
  topic("digestion", "DIGESTION", "digestive");
}

void content_kidneys() {
  topic("kidneys", "KIDNEYS", "nephron", "organ_map");
}

void content_hormones() {
  topic("hormones", "HORMONES", "organ_map");
}

void content_immune() {
  topic("immune", "IMMUNE SYSTEM", "organ_map");
}
