#!/usr/bin/env python3
"""Build Rick_Med_School/Content.pde from the study content JSON files in ../content/.

    python3 tools/build_content.py [content_dir]

Each content file holds some topics (4 levels each: lessons, multiple-choice
and click-the-part questions) plus notes for the diagram parts it owns.
Topics that have no file yet become empty stubs so the game still runs."""
import json, os, sys, glob

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "content")
OUT = os.path.join(ROOT, "Rick_Med_School", "Content.pde")

ORDER = ["cells", "bones", "muscles", "nervous", "heart", "lungs", "digestion", "kidneys", "hormones", "immune"]
TITLES = {"cells": "CELLS", "bones": "BONES", "muscles": "MUSCLES", "nervous": "NERVOUS SYSTEM", "heart": "HEART & BLOOD",
          "lungs": "LUNGS", "digestion": "DIGESTION", "kidneys": "KIDNEYS", "hormones": "HORMONES", "immune": "IMMUNE SYSTEM"}
DIAGRAMS = {"cells": ["cell"], "bones": ["skeleton"], "muscles": ["muscles"], "nervous": ["neuron", "brain"], "heart": ["heart"],
            "lungs": ["lungs"], "digestion": ["digestive"], "kidneys": ["nephron", "organ_map"], "hormones": ["organ_map"], "immune": ["organ_map"]}

def j(s):
    s = "" if s is None else str(s)
    bad = [c for c in s if ord(c) < 32 or ord(c) > 126]
    if bad:
        raise SystemExit(f"non-ASCII text {bad[:3]} in: {s[:80]}")
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

topics, parts = {}, []
files = sorted(glob.glob(os.path.join(SRC, "*.json")))
for f in files:
    d = json.load(open(f))
    for t in d.get("topics", []):
        topics[t["topic"]] = t
    parts += d.get("parts", [])

out = ["// GENERATED by tools/build_content.py from the fact-checked study content in content/*.json.",
       "// Edit the JSON and re-run the script rather than editing this file.", "",
       "void loadContent() {"]
out += [f"  content_{k}();" for k in ORDER]
dias = sorted({p["diagram"] for p in parts})
out += [f"  parts_{d}();" for d in dias]
out += ["}", ""]
counts = []
for k in ORDER:
    out.append(f"void content_{k}() {{")
    out.append(f"  topic({j(k)}, {j(TITLES[k])}" + "".join(", " + j(d) for d in DIAGRAMS[k]) + ");")
    t = topics.get(k)
    nq = nl = 0
    if t:
        for lev in sorted(t["levels"], key=lambda l: l["level"]):
            out.append(f"  level({lev['level']});")
            for le in lev["lessons"]:
                out.append(f"  lesson({j(le['id'])}, {j(le['title'])}, {j(le['fact'])}, {j(le['rick'])}, {j(le.get('diagram', ''))}, {j(le.get('part', ''))});")
                nl += 1
            for q in lev["questions"]:
                if q["type"] == "mcq":
                    ch = ", ".join(j(c) for c in q["choices"])
                    out.append(f"  mcq({j(q['id'])}, {j(q['q'])}, new String[] {{ {ch} }}, {int(q['answer'])}, {j(q['explain'])}, {j(q['rick'])});")
                else:
                    out.append(f"  label({j(q['id'])}, {j(q['diagram'])}, {j(q['part'])}, {j(q['q'])}, {j(q['explain'])}, {j(q['rick'])});")
                nq += 1
    out.append("}")
    out.append("")
    counts.append(f"{k}: {nl} lessons, {nq} questions" + ("" if t else "  (NO CONTENT YET)"))
for d in dias:
    out.append(f"void parts_{d}() {{")
    for p in parts:
        if p["diagram"] == d:
            out.append(f"  partInfo({j(p['diagram'])}, {j(p['id'])}, {j(p['name'])}, {j(p['desc'])}, {j(p['rick'])});")
    out.append("}")
    out.append("")
open(OUT, "w").write("\n".join(out))
print(f"wrote {OUT} from {len(files)} file(s)")
print("\n".join("  " + c for c in counts))
print(f"  part notes: {len(parts)}")
